### ISSUE TITLE
UserWarning: multiple_iterators not implemented for CRAM 

### ISSUE THREAD

**Issue by LNGDingj** [Illumina/Gauchian#2]
When running with .cram file, got the following warnings
/gauchian/depth_calling/snp_count.py:131: UserWarning: **multiple_iterators not implemented for CRAM** ignore_orphan=False
/gauchian/depth_calling/haplotype.py:189: UserWarning: **multiple_iterators not implemented for CRAM** min_base_quality=13

Will these warnings affect the quality of calls?

**Comment by xiao-chen-xc** [comment]
Hi @LNGDingj, the warnings are an expected behavior of pysam. They won't affect the quality of calls.
